name: weathercast
description: A simple Weather App demonstrating Flutter

version: 0.5.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^0.5.0

  mvc_application:
#    path: ../../packages/mvc_application
    git:
      url: git://github.com/AndriousSolutions/mvc_application.git

  http:
    #^0.12.0

  equatable:
    #^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/